Parameterize tests for Answer interface
agoscinski/scicode-widgets-unofficial pull request #6
Opened 2022-07-15 06:16 UTC by jprado1

I use the `parameterized` library to parameterise tests for the Answer interface with a @parameterized_class decorator:

`@parameterized_class(("name","tested_answer"), [
   ("TextareaAnswer",TextareaAnswer(), ),
   ("CodeDemo",CodeDemo(
            code_input=  WidgetCodeInput(
                function_name="name", 
                function_parameters="",
                docstring="""""",
                function_body="""body"""),
            input_parameters_box=None,
            visualizers=None,
            update_visualizers=None,
            code_checker=None,
            separate_check_and_update_buttons=False,
            update_on_input_parameter_change=False
), )
])`

creates two tests with named `TestAnswerRegistry_{testnumber}_{name}`. parameterized_class is used in order to use parameters in setUp and eventually tearDown. To add new parameterized tests, it suffices to add tuples (name : String, answer : Answer) to the list defined inside the decorator.

2022-07-15 09:34 UTC, agoscinski commented on python/tests/tests.py
We just need a `tearDown` function which deletes the `test-MaxMustermann` json file if it exists after each tests. This is important, because when multiple tests will access the json file, the test can rely on that they created the `test-MaxMustermann.json`file and they don't read the from a file created for a different test.

2022-07-27 10:44 UTC, jprado1 commented
# 1, Fixed typo in SupressStdOutput class name
# 2. Corrected test for update() and created test check() when there is no button
# 3. removed old TODOs and general clean up
# 4. Adapted AnswerTest with respect to fix of PR #7 (but did not implement the respective test of this PR)

2022-08-22 08:14 UTC, agoscinski requested changes
Looks good, just one minor change and it can be merged

2022-08-22 08:14 UTC, agoscinski commented on python/examples/visual_cues_examples.ipynb
> +    "from ipycanvas import Canvas\n",
Can you add one cell before that with
```!pip install ipycanvas```
so tox can also run all notebooks

2022-08-30 08:18 UTC, jprado1 commented on python/examples/visual_cues_examples.ipynb
> +    "from ipycanvas import Canvas\n",
Done, will merge

2022-08-30 08:18 UTC, merged